### ISSUE TITLE
Tutorial Week 5 - Observer pattern (Chat application)

### ISSUE THREAD

**Issue by jodavimehran** [jodavimehran/soen344-tutorial#7]
Extend the Observer pattern shown in the lectures, to add a console-based chat client.

![image](https://user-images.githubusercontent.com/55111960/73959648-04492c80-48e0-11ea-8e63-b43308d48889.png)

**Comment by thomasgauvin** [comment]
Steps:

1) Create a Console application that echo the user input
2) Change the console app to send the input to the server by using ChatAccess class
3) Change to update console by using Observer pattern
